repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix] # Exit non-zero if fixes are made
      - id: ruff-format # Corrected ID
        args: [--respect-gitignore]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0 # Use a recent version of mypy
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]
        # additional_dependencies: [types-pyyaml, types-tqdm, types-psutil, types-paramiko] # Add as needed based on mypy errors
  - repo: local
    hooks:
      - id: uv-lock-check
        name: Check uv.lock consistency
        entry: bash -c 'make lock && git diff --exit-code --quiet uv.lock || (echo "uv.lock was updated by make lock, please stage it." && exit 1)'
        language: system
        pass_filenames: false
        stages: [commit, push] # Run on commit and push for safety
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 # Updated rev
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: debug-statements
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf] 